region: ap-southeast-2
domain: appleed.com
vpcId: vpc-0681d6c49d777a3ee # VPC POC 172.31.0.0/16
vpcSubnetId: subnet-0e5ac272a5af148e8 # subnet-pvt-ap2c-poc
securityGroupId: sg-0d2e6bd437076c470 # sg_linux_mgmt_pvt
projectName: demo
env: poc
instanceType: t2.micro
ami: ami-093d6bca87ee43652  # AMI ID. Make sure this AMI exists in your AWS account
privateKeyLocation: "../test/aws-private.pem"
hostGroup: "[webserver]"
hostPath: "../test/inventory/hosts"
hostString: "ansible_ssh_user=ec2-user ansible_ssh_private_key_file=../test/aws-private.pem"